### PR TITLE
Handle failed notifications so that they get dismissed and click events work

### LINKED ISSUE #51: Unsuccessful download notification reappearing after being dismissed
This occurs while another download is active

### PR DESCRIPTION
**Pull request by xrigau**
Title ^

### Before

the notifications for a failed download wouldn't fire any intent on click, and they'd reappear after being dismissed every time the DownloadService was recreated.

### After

the click works and they don't reappear after being dismissed

Fixes #51 , #143

### CODE REVIEW

**Comment by blundell** [comment]
LGTM :+1:

**Comment by ronocod** [comment]
:+1: LGTM2

File: library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java [hunk 1]
```diff
@@ -120,14 +120,18 @@ private void buildActionIntents(String tag, int type, Collection<DownloadBatch>
         DownloadBatch batch = cluster.iterator().next();
         long batchId = batch.getBatchId();
         int batchStatus = batch.getStatus();
+
         if (type == SynchronisedDownloadNotifier.TYPE_ACTIVE || type == SynchronisedDownloadNotifier.TYPE_WAITING) {
             // build a synthetic uri for intent identification purposes
             Uri uri = new Uri.Builder().scheme("active-dl").appendPath(tag).build();
 
-            Intent clickIntent = createClickIntent(ACTION_LIST, batchId, batchStatus, uri);
+            Intent clickIntent = createClickIntent(ACTION_LIST, batchId, batchStatus, uri); // TODO: the Uri doesn't seem to be ever read
```
Comment (xrigau) [inline library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java]: #168
