### PR TITLE
Remove completed notification on delete

### LINKED ISSUE #300: Delete status updates not occurring
## Steps to reproduce
- Download an asset using the download manager sample app.
- Once complete press the delete all button
**Expected:** Statuses show as deleted **Actual:** Statuses show as deleted 💯 

- Download an asset using the download manager sample app.
- Once complete swipe away the app from recents killing the service etc.
- Restart the app, you should see the last status of download complete.
- Press the delete button
**Expected:** Should show status as being deleted **Actual:** Status shows previous state of complete

## Solution 
When creating the `download-manager` from scratch we retrieve all of the batches from the db and then call `download` on all of the downloads that have not already been downloaded. The `download` attaches callbacks on the batch which you will receive when calling `LiteDownloadManagerCommands.addDownloadBatchCallback(DownloadBatchCallback downloadBatchCallback);`. Here's the thing though, in the `LiteDownloadManagerDownloader` we check for whether a downloaded is downloaded before setting up these callbacks. Downloaded? No callbacks for you.

Should be a relatively easy fix supplying the callback regardless of state.

### PR DESCRIPTION
**Pull request by MechaRyRy**
### Problem
When trying to fix #300 I found that when downloads complete in the sample app and a user taps delete the notifications are still persisted, even though they don't exist anymore 😬 

### Solution
Make sure that we remove a notification that corresponds to a download that is deleted. 

I have created a `NotificationDispatcher` to encapsulate the logic related to sending notifications in one class rather than continue to include it in the already bloated `Downloader` class. 

Send a `NotificationInformation` when performing a dismiss on notifications so we can have the notification manager remove a specific notification. This would be the notifications not bound to the service anymore.

### Screen Capture

Before | After
--- | ---
delete_notifications_before | delete_notification_after

### CODE REVIEW

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+    private DownloadService downloadService;
+
+    NotificationDispatcher(Object waitForDownloadService, NotificationCreator<DownloadBatchStatus> notificationCreator) {
+        this.waitForDownloadService = waitForDownloadService;
+        this.notificationCreator = notificationCreator;
+    }
+
+    void updateNotification(DownloadBatchStatus downloadBatchStatus) {
+        WaitForDownloadService.<Void>waitFor(downloadService, waitForDownloadService)
```
Comment (zegnus) [inline library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: Is this a blocking call?

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+                .thenPerform(executeUpdateNotification(downloadBatchStatus));
+    }
+
+    private WaitForDownloadService.ThenPerform.Action<Void> executeUpdateNotification(DownloadBatchStatus downloadBatchStatus) {
+        return () -> {
+            NotificationInformation notificationInformation = notificationCreator.createNotification(downloadBatchStatus);
+
+            if (downloadBatchStatus.status() == DELETION) {
```
Comment (jszmltr) [inline library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: How about : 
```
if () {
} else if (){
} else {
}
return null;
```

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 1 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: It's only blocking the current thread if the `download-service` doesn't exist. Given that the `Downloader` would also be blocked I don't think this is an issue.

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 2 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: I prefer the quickness and readability of the `if -> return` 😄  I guess its a preference thing!

Comment (jszmltr) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: What I don't like in this scenario that `else` is not really highlighted enough. But don't mind really.

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 1 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: Ah right sorry. This is blocking yes. The `Downloader` waits for the service before performing the `download` on the `DownloadBatch` the batch then calls through to this dispatcher. So from what I understand this will all be on the `executor`. Correct me if I am wrong.

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 2 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: 6ffb008

**Comment by MechaRyRy** [comment]
@zegnus Updated the deleted notification rather than just removing. This means that there is an unused method on the `Service`, maybe this should be customisable by the client?
deleted

**Comment by zegnus** [comment]
@Mecharyry Regarding offering a custom notification for just the deleted ones, the current API provides already a callback for providing a notification, is a client wants to customise it they can just do it providing now. We can always extend it and provide customisations for just the downloaded and the deleted statuses but is good enough as it is now in my opinion (we do not restrict functionalities and we are still flexible enough)

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 1 above)
Comment (zegnus) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: Yes you are right, shall we use the working thread annotation? ;)

File: library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java [hunk 3]
```diff
@@ -283,20 +285,36 @@ private CallbackThrottleCreator getCallbackThrottleCreator(CallbackThrottleCreat
...
-            int percentageDownloaded = payload.percentageDownloaded();
-            int bytesFileSize = (int) payload.bytesTotalSize();
-            int bytesDownloaded = (int) payload.bytesDownloaded();
             String title = downloadBatchTitle.asString();
-            String content = percentageDownloaded + "% downloaded";
+            String content = "Deleted";
 
             return builder
-                    .setProgress(bytesFileSize, bytesDownloaded, NOT_INDETERMINATE)
                     .setSmallIcon(notificationIcon)
```
Comment (zegnus) [inline library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java]: This code is also reused in the else, shall we try to reuse as much as possible?

Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java]: Can do 👍

**Comment by zegnus** [comment]
@Mecharyry sorry you were right, I missed the `stack` notification. Yeah we should add it as part of the customisation otherwise there is no way that the client can modify that. Let's add a task for it.

File: library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java (hunk 3 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java]: 2b040c5

File: library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java (hunk 1 above)
Comment (MechaRyRy) [reply library/src/main/java/com/novoda/downloadmanager/NotificationDispatcher.java]: 0c35ee2

**Review by zegnus — APPROVED** [review]
